<?php

namespace ContainerTWqkQs7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SeMQrOWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.seMQrOW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.seMQrOW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blague' => ['privates', '.errored..service_locator.seMQrOW.App\\Entity\\Blagues', NULL, 'Cannot autowire service ".service_locator.seMQrOW": it needs an instance of "App\\Entity\\Blagues" but this type has been excluded in "config/services.yaml".'],
            'blaguesRepository' => ['privates', 'App\\Repository\\BlaguesRepository', 'getBlaguesRepositoryService', true],
        ], [
            'blague' => 'App\\Entity\\Blagues',
            'blaguesRepository' => 'App\\Repository\\BlaguesRepository',
        ]);
    }
}
