<?php

namespace ContainerTWqkQs7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VjV598aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vjV598a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vjV598a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blaguesRepository' => ['privates', 'App\\Repository\\BlaguesRepository', 'getBlaguesRepositoryService', true],
        ], [
            'blaguesRepository' => 'App\\Repository\\BlaguesRepository',
        ]);
    }
}
