<?php

namespace ContainerGl9wnij;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__M_MRbrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..M.MRbr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..M.MRbr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BlaguesController::delete' => ['privates', '.service_locator.seMQrOW', 'get_ServiceLocator_SeMQrOWService', true],
            'App\\Controller\\BlaguesController::edit' => ['privates', '.service_locator.seMQrOW', 'get_ServiceLocator_SeMQrOWService', true],
            'App\\Controller\\BlaguesController::index' => ['privates', '.service_locator.vjV598a', 'get_ServiceLocator_VjV598aService', true],
            'App\\Controller\\BlaguesController::new' => ['privates', '.service_locator.vjV598a', 'get_ServiceLocator_VjV598aService', true],
            'App\\Controller\\BlaguesController::show' => ['privates', '.service_locator.o0jxhru', 'get_ServiceLocator_O0jxhruService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.0CRkV7m', 'get_ServiceLocator_0CRkV7mService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.0CRkV7m', 'get_ServiceLocator_0CRkV7mService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BlaguesController:delete' => ['privates', '.service_locator.seMQrOW', 'get_ServiceLocator_SeMQrOWService', true],
            'App\\Controller\\BlaguesController:edit' => ['privates', '.service_locator.seMQrOW', 'get_ServiceLocator_SeMQrOWService', true],
            'App\\Controller\\BlaguesController:index' => ['privates', '.service_locator.vjV598a', 'get_ServiceLocator_VjV598aService', true],
            'App\\Controller\\BlaguesController:new' => ['privates', '.service_locator.vjV598a', 'get_ServiceLocator_VjV598aService', true],
            'App\\Controller\\BlaguesController:show' => ['privates', '.service_locator.o0jxhru', 'get_ServiceLocator_O0jxhruService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.0CRkV7m', 'get_ServiceLocator_0CRkV7mService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.0CRkV7m', 'get_ServiceLocator_0CRkV7mService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BlaguesController::delete' => '?',
            'App\\Controller\\BlaguesController::edit' => '?',
            'App\\Controller\\BlaguesController::index' => '?',
            'App\\Controller\\BlaguesController::new' => '?',
            'App\\Controller\\BlaguesController::show' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BlaguesController:delete' => '?',
            'App\\Controller\\BlaguesController:edit' => '?',
            'App\\Controller\\BlaguesController:index' => '?',
            'App\\Controller\\BlaguesController:new' => '?',
            'App\\Controller\\BlaguesController:show' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
