<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGl9wnij\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGl9wnij/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGl9wnij.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGl9wnij\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGl9wnij\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gl9wnij',
    'container.build_id' => '9937c267',
    'container.build_time' => 1689162199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGl9wnij');
